version: '3.7'
services:
#  lifx:
#    image: delfick/lifx-photons-interactor
#    environment:
#      - TZ=America/Montreal
#    network_mode: host
#    volumes:
#      - ./config/:/project/config/

  api:
    build: .
    environment:
      - PORT=80
      - LIFX_HOSTNAME=192.168.0.44:6100
    ports:
      - "9999:80"