version: '3.7'
services:
  api:
    build: .
    environment:
      - PORT=80
      - LIFX_HOSTNAME=192.168.0.44:6100
    volumes:
      - ./config/config.json:/lib/lifx_control/config/config.json
    ports:
      - "9999:80"
    restart: unless-stopped