version: '3.7'
services:
  lifx:
    image: delfick/lifx-photons-interactor
    environment:
      - TZ=America/Montreal
    restart: always
    network_mode: host
    volumes:
      - ./config/:/project/config/
    ports:
      - "6100:6100"

  api:
    build: .
    environment:
      - PORT=80
      - LIFX_HOSTNAME=192.168.0.26:6100
    ports:
      - "9999:80"
    restart: always
