version: '3.7'
services:
  lifx:
    image: delfick/lifx-photons-interactor
    environment:
      - TZ=America/Montreal
    restart: always
    network_mode: host
    volumes:
      - ./config/lifx.yml:/project/config
    ports:
      - "6100:80"

  api:
    build: .
    environment:
      - PORT=80
    ports:
      - "9999:80"
    restart: always
